dist: xenial

language: python

matrix:
  include:
    - env: TOX_ENV=py37-django32,py37-django40,py37-django41,py37-django42
      python: "3.7"
    - env: TOX_ENV=py38-django32,py38-django40,py38-django41,py38-django42
      python: "3.8"
    - env: TOX_ENV=py39-django32,py39-django40,py39-django41,py39-django42
      python: "3.9"
    - env: TOX_ENV=py310-django32,py310-django40,py310-django41,py310-django42
      python: "3.10"
    - env: TOX_ENV=py311-django32,py311-django40,py311-django41,py311-django42
      python: "3.11"

install:
  - pip install tox

script: tox . -e $TOX_ENV