# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 08:51
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import migrations, models


def create_super_admin(admin, password):
    if not User.objects.filter(username=admin).first():
        User.objects.create_superuser(admin, "", password)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0005_alter_user_last_login_null")
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('handsome', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(
            lambda apps, schema_editor: create_super_admin("admin", "123456"))
    ]
